[build]
command = "export VOLC_ACCESSKEY=$VOLC_ACCESSKEY && export VOLC_SECRETKEY=$VOLC_SECRETKEY && python -m pip install --upgrade pip && pip install -r requirements.txt && python server.py"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.9"
PIP_NO_CACHE_DIR = "true"
NODE_VERSION = "18"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
directory = "services"
node_bundler = "esbuild"

[dev]
framework = "#custom"
command = "python server.py"
port = 8000
targetPort = 8000