[build]
command = "pip install -r requirements.txt && python server.py"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
directory = "services"
node_bundler = "esbuild"

[dev]
framework = "#custom"
command = "python server.py"
port = 8000
targetPort = 8000